import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.proxy.example.hello.useQuery({ text: "Basil" });
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container flex flex-col items-center justify-center min-h-screen p-4 mx-auto">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Create <span className="text-purple-300">T3</span> App
        </h1>
        <div className="flex items-center justify-center w-full pt-6 text-2xl text-blue-500">
          {hello.data ? <div>{hello.data.secondHello}</div> : <p>Loading..</p>}
        </div>
        <div className="flex items-center justify-center w-full pt-6 text-2xl text-blue-500 mb-8">
          {hello.data ? <div>{hello.data.greeting}</div> : <p>Loading..</p>}
        </div>
        <div>
          {!session ? (
            <button
              className="rounded-xl p-10  btn-primary"
              onClick={() => signIn()}
            >
              Sign In
            </button>
          ) : (
            <div>
              <h2>You are signed in</h2>
              <button
                className="rounded-xl p-10 btn-primary"
                onClick={() => signOut()}
              >
                Sign Out
              </button>
            </div>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;

// Technology component
